#ifndef PARAMETERS_H
#define PARAMETERS_H

#define BASIC_HOTSUS
#define MAX_NUM_NODES 4
#define MAX_NUM_SIGNATURES 3
#define MAX_NUM_TRANSACTIONS 400
#define MAX_NUM_GROUPMEMBERS 100
#define PAYLOAD_SIZE 0

#endif
